name: Build PHP8 Images
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Prepare Multiarch Images
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build Nginx Alpine Image
        uses: docker/build-push-action@v2
        with:
          context: php8-nginx
          platforms: linux/amd64,linux/arm64
          push: true
          tags: boyander/php8-wordpress:nginx
      - name: Build Apache Image
        uses: docker/build-push-action@v2
        with:
          context: php8-apache
          platforms: linux/amd64,linux/arm64
          push: true
          tags: boyander/php8-wordpress:apache
